plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.4'
    id 'io.spring.dependency-management' version '1.1.6'
}

group = 'com.dsa_practise'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}
ext {
    aspectjVersion = '1.9.22'
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    // AspectJ tools
    implementation "org.aspectj:aspectjtools:${aspectjVersion}"
    // AspectJ runtime
    runtimeOnly "org.aspectj:aspectjrt:${aspectjVersion}"
    // Log4j 2 API
    implementation 'org.apache.logging.log4j:log4j-api:2.20.0'

    // Log4j 2 Core
    implementation 'org.apache.logging.log4j:log4j-core:2.20.0'
    // https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-data-jpa
    implementation("org.springframework.boot:spring-boot-starter-data-jpa:3.3.5")


    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}
